// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> ar = {
    "onBoardingTitle1":
        "من المؤكد انك مللت من محاوله تنظيم حياتك وسوف نساعدك في فعل ذلك",
    "onBoardingDec1": "سوف ننظم مهامتك واعمالك الماديه ووقتك ",
    "onBoardingTitle2": "وقتك واعمالك التجاريه في  ايد ثمينه",
    "onBoardingTitle3": "نحن هنا من اجلك ",
    "hallo": "مرحبا,...",
    "EmailHint": "ادخل اميلك الالكتروني",
    "passwordHint": "ادخل كلمه المرور ",
    "signUp": "انشاء حساب ",
    "hi": "اهلا",
    "SignUpNow": "انشىء حسابك الجديد الان ",
    "NameHint": "ادخل اسمك",
    "again": "مجددا",
    "phoneHint": "ادخل رقم هاتفك ",
    "Done": "تسجيل",
    "Single": "اعز",
    "Married": "متزوج",
    "Business": "تاجر",
    "AddTask": "اضافه مهمه",
    "Tasks": "مهمات",
    "Balance ": "الرصيد",
    "analytics": "التحليلات",
    "Settings": "اعدادات",
    "EnterSalary": "أدخل راتبك الشهري ",
    "SalaryHint": "ادخل دخلك الشهري ",
    "Home": "المنزل",
    "clothes": "الملابس",
    "Teaching": "التعليم ",
    "food": "طعام",
    "Fun": "التمتع",
    "Travel": "السفر",
    "GainedMoney": "كسب المال",
    "SheetTitle": "لماذا صرفت هذا المال",
    "ReasonHint": "ما سبب صرف هذا المال؟",
    "when": "متي؟",
    "HowMuch": "كم صرفت من المال ؟",
    "okay": "حسنا!",
    "SheetTitle2": " اكتساب المال",
    "ReasonGainMoney": "كيف اكتسبت هذا المال ؟",
    "HowMuchGain": "كم كسبت من المال ؟",
    "MoneyNotFound": "انت لم تصرف مال حتي الان 🥰",
    "DarkMood": "الوضع الليلي",
    "language": "اللغه",
    "Reminder": "التذكيرات",
    "AboutUs": "من نحن ",
    "ContactUs": "تواصل معنا",
    "ChatBoot": "محادثه الربوت",
    "titleLogin": "تسجيل دخول",
    "MoneySaving ": "ادخار المال",
    "ReminderDesc": "الغاء تنبيهات اضافه المهمات او المال او تشغيلها",
    "Title": "عنوان",
    "TitleHint": "اكتب عنوان مهمتك",
    "Description ": "الوصف",
    "DescriptionHint ": "اكتب وصف مهتمك",
    "time": "الوقت",
    "EnterTime": "ادخل الوقت",
    "Date": "التاريخ",
    "EnterDate": "ادخل التاريخ ",
    " Repeat": "التكرار",
    "priority": "الاولويه",
    "High": "عالي ",
    "Medium": "متوسط",
    "Low": "منخفض",
    "ChatWithUs": "تحدث معنا ",
    "firstMassage":
        "مرحبًا ، أنا مساعد الروبوت الخاص بك. يمكنني مساعدتك في إدارة مهامك وميزانيتك. ماذا تريد ان تفعل؟",
    "hiuser": "مرحبا ايها المستخدم",
    "letsgo": "هيا بنا",
    "okaygreat": "هذا جيد",
    "whatTimeChat": "ماهو وقت مهمتك؟",
    "whatDescriptionChat": "ما هو وصف مهمتك؟",
    "whatTitleChat": "ما هو عنوان مهمتك؟",
    "whatDateChat": "ماهو تاريخ مهمتك ؟",
    "howMuchPay": "كم دفعت من اجل ذلك؟",
    "WhyPayMoney": "لماذا دفعت هذا المال؟",
    "whichCategories ": " في أي فئة تريد وضعها؟",
    "whenPay": "متي دفعت هذا المال ؟",
    "SuggestionWords": "الكلمات المقترحه",
    "WannaTask": "اريد اضافه مهمه جديده",
    "wannaMoney": "أريد إضافة معاملة مالية جديدة",
    "MessageHint": "اكتب رسالتك",
    "Healthcare ": "الرعايه بالصحه",
    "dontHaveTask": "ليس لديك أي مهمة 🥰 ، أتمنى لك يومًا سعيدًا",
    "Imgreat": "انا بخير",
    "ImjoeRobot": "انا الروبوت جو",
    "Continue": "استكمال",
    "cancel": "الغاء",
    "AddTaskReminder": "التذكير باضافه مهمه جديده",
    "AddMoneyReminder": "التذكير باضافه معاملة مالية جديدة",
    "Facebook": "فيس بوك",
    "instagram": "انستجرام",
    "resetBudget": "اعاده تعيين الميزانيه",
    "ChangeIncome": "  تغيير الدخل الشهري",
    "descContact": "تواصل معنا لاي للمساعده او اقتراح",
    "IncomeMoney": "الدخل الشهري",
    "IncomeMoneyDesc": "اعد تعيين ميزانيتك الشهريه ",
    "Never": "ابدا",
    "Monthly": "شهريا",
    "Weekly": "اسبوعيا",
    "Daily": "يوميا",
    "repeat": "التكرار",
    "DevelopedBy": "صنع بواسطه /يوسف احمد ",
    "Version": "Version:1.0.0",
    "Filters": "فلتر",
    "dayOfWeek": "اليوم الاسبوعي للتنبيه",
    "Sunday": "الاحد",
    "Monday": "الاثنين",
    "Tuesday": "الثلاثاء",
    "Wednesday": "الاربعاء",
    "Thursday": "الخميس",
    "Friday": "الجمعه",
    "Saturday": "السبت",
    "dateReminder": "تاريخ بدايه التنبيه",
    "SavingTitle": "ادخار المال",
    "ReasonSaving": "لماذا ستدخر هذا المال؟",
    "moneySaving":"كم ستدخر من المال؟",
    "Edit":"تعديل",
    "dismiss":"تعطيل",
    "Activation":"تنشيط",
  };
  static const Map<String, dynamic> en = {
    "onBoardingTitle1":
        "you must be bored from trying to organize your time,we will help you",
    "onBoardingDec1": "we will organize your tasks,business and time",
    "onBoardingTitle2": "your time and business is in the Right hands",
    "onBoardingTitle3": "we are here for you 24/7",
    "hallo": "hello again,...",
    "EmailHint": "Enter your email,....",
    "passwordHint": "Enter your password,...",
    "signUp": "SignUp",
    "hi": "hi",
    "SignUpNow": "Sign Up now,...",
    "NameHint": "Enter your name,...",
    "again": "again",
    "phoneHint": "Enter your phone Number,..",
    "Done": "Done",
    "Single": "Single",
    "Married": "Married",
    "Business": "Business",
    "AddTask": "Add Task",
    "Tasks": "Tasks",
    "Balance ": "Balance ",
    "analytics": "analytics",
    "Settings": "Settings",
    "EnterSalary": "Enter your Salary",
    "SalaryHint": "Write your salary ",
    "Home": "Home",
    "clothes": "clothes",
    "Teaching": "Teaching",
    "food": "Food",
    "Fun": "Fun",
    "Travel": "Travel",
    "GainedMoney": "Gained Money",
    "SheetTitle": "Why you spend Money ?",
    "ReasonHint": "Reason for spending Money?",
    "when": "When?",
    "HowMuch": " How much did you spend?",
    "okay": "Okay!",
    "SheetTitle2": "Gain Money",
    "ReasonGainMoney": "How you gain this Money?",
    "HowMuchGain": "How much you gain?",
    "MoneyNotFound": "you didn't spend any money until now ,good boy🥰",
    "DarkMood": "Dark Mood",
    "language": "Language ",
    "Reminder": "Reminder",
    "AboutUs": "About Us",
    "ContactUs": "Contact Us",
    "ChatBoot": "chat boot",
    "titleLogin": "Login",
    "MoneySaving ": "Money saving ",
    "ReminderDesc": "Cancel tasks and money reminder or turn on it",
    "Title": "Title",
    "TitleHint": "Write title of your task ",
    "Description ": "Description ",
    "DescriptionHint ": "Write description of your task ",
    "time": "Time",
    "EnterTime": "Enter Time of your task",
    "Date": "Date",
    "EnterDate": "Enter Date",
    " Repeat": "Repeat",
    "priority": "Priority",
    "High": "High",
    "Medium": "Medium ",
    "Low": "Low",
    "ChatWithUs": "Chat with us",
    "firstMassage":
        "Hi, I am your robot assistant. I can help you to manage your tasks and budget. What would you like to do?",
    "hiuser": "hi,user",
    "letsgo": "lets go",
    "okaygreat": "okay, great",
    "whatTimeChat": "what time of your task?",
    "whatDescriptionChat": "What is your task's description ?",
    "whatTitleChat": "What is your task's title?",
    "whatDateChat": "what date of your task?",
    "howMuchPay": "how much you pay for it?",
    "WhyPayMoney": "why you pay this money?",
    "whichCategories ": "which category do you want to put it in?",
    "whenPay": "when you pay for it?",
    "SuggestionWords": "Suggestion words",
    "WannaTask": "I want to add new task",
    "wannaMoney": "I want to add new financial transaction",
    "MessageHint": "Type Your message ",
    "Healthcare ": "Health care ",
    "dontHaveTask": "you don't have any task 🥰,I wish nice day to you ❤️",
    "Imgreat": "I'm great",
    "ImjoeRobot": "I'm joe Robot",
    "Continue": "Continue",
    "cancel": "Cancel",
    "AddTaskReminder": "Add Task Reminder",
    "AddMoneyReminder": "Add Money Reminder",
    "Facebook": "Facebook",
    "instagram": "instagram",
    "resetBudget": "reset Budget",
    "ChangeIncome": "Change your monthly income",
    "descContact": "contact us for any help or suggestions",
    "IncomeMoney": "income Money",
    "IncomeMoneyDesc": "reset your monthly income ",
    "Never": "Never",
    "Monthly": "Monthly",
    "Weekly": "Weekly",
    "Daily": "Daily",
    "repeat": "repeat",
    "DevelopedBy": "Developed by:Eng/Youssef ahmed",
    "Version": "Version:1.0.0",
    "Filters": "Filters",
    "dayOfWeek": "Day of week",
    "Sunday": "Sunday",
    "Monday": "Monday",
    "Tuesday": "Tuesday",
    "Wednesday": "Wednesday",
    "Thursday": "Thursday",
    "Friday": "Friday",
    "Saturday": "Saturday",
    "dateReminder": "Date of start reminder",
    "SavingTitle": "Saving money",
    "ReasonSaving": "Why you will saving this money?",
    "moneySaving": "how much you will saving?",
    "Edit": "Edit",
    "dismiss": "dismiss",
    "Activation": "Activation",

  };
  static const Map<String, Map<String, dynamic>> mapLocales = {
    "ar": ar,
    "en": en
  };
}
